# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'final-project' do

  use_frameworks!

  pod 'Alamofire', '~> 5.5'
  pod 'Kingfisher', '~> 7.0'


end
